import { parseMerchants } from 'utils/merchant-dropdown-utils'

const merchantRawData = {
  'accessible': true,
  'alertEmail': 'technicalsupport@bambora.com',
  'children': [
    {
      'accessible': true,
      'alertEmail': 'support@devcode.se',
      'children': [
        {
          'accessible': true,
          'alertEmail': 'support@devcode.se',
          'children': [
            {
              'accessible': true,
              'alertEmail': 'support@devcode.se',
              'children': [],
              'childrenId': [],
              'companyName': 'DevCode Template Merchant last ',
              'companyUrl': null,
              'contactEmail': 'support@devcode.se',
              'contactPerson': 'DevCode Support, Template MasterTest',
              'contactPhone': '00 46 8 520253 20',
              'created': null,
              'createdBy': null,
              'customerId': 2,
              'description': null,
              'enabled': true,
              'event': 'UPDATE',
              'id': 10001100,
              'message': null,
              'name': 'Sub sub sub mid - 1',
              'nextVersion': 2,
              'parentId': 0,
              'platform': '',
              'status': 'ENABLED',
              'updated': null,
              'updatedBy': null
            }
          ],
          'childrenId': [10001100],
          'companyName': 'DevCode Template Merchant last ',
          'companyUrl': null,
          'contactEmail': 'support@devcode.se',
          'contactPerson': 'DevCode Support, Template MasterTest',
          'contactPhone': '00 46 8 520253 20',
          'created': null,
          'createdBy': null,
          'customerId': 2,
          'description': null,
          'enabled': true,
          'event': 'UPDATE',
          'id': 100011,
          'message': null,
          'name': 'Sub sub mid - 1',
          'nextVersion': 2,
          'parentId': 0,
          'platform': '',
          'status': 'ENABLED',
          'updated': null,
          'updatedBy': null
        }
      ],
      'childrenId': [100011],
      'companyName': 'DevCode Template Merchant',
      'companyUrl': null,
      'contactEmail': 'support@devcode.se',
      'contactPerson': 'DevCode Support, Template MasterTest',
      'contactPhone': '00 46 8 520253 20',
      'created': null,
      'createdBy': null,
      'customerId': 2,
      'description': null,
      'enabled': true,
      'event': 'UPDATE',
      'id': 10001,
      'message': null,
      'name': 'Sub mid - 1',
      'nextVersion': 2,
      'parentId': 0,
      'platform': '',
      'status': 'ENABLED',
      'updated': null,
      'updatedBy': null
    },
    {
      'accessible': true,
      'alertEmail': 'support@devcode.se',
      'children': [],
      'childrenId': [],
      'companyName': 'DevCode Template Merchant disabled',
      'companyUrl': null,
      'contactEmail': 'support@devcode.se',
      'contactPerson': 'DevCode Support, Template MasterTest',
      'contactPhone': '00 46 8 520253 20',
      'created': null,
      'createdBy': null,
      'customerId': 2,
      'description': null,
      'enabled': false,
      'event': 'UPDATE',
      'id': 10002,
      'message': null,
      'name': 'Sub mid - 2',
      'nextVersion': 2,
      'parentId': 0,
      'platform': '',
      'status': 'DISABLED',
      'updated': null,
      'updatedBy': null
    },
    {
      'accessible': true,
      'alertEmail': 'support@devcode.se',
      'children': [],
      'childrenId': [],
      'companyName': 'DevCode Template Merchant',
      'companyUrl': null,
      'contactEmail': 'support@devcode.se',
      'contactPerson': 'DevCode Support, Template MasterTest',
      'contactPhone': '00 46 8 520253 20',
      'created': null,
      'createdBy': null,
      'customerId': 2,
      'description': null,
      'enabled': true,
      'event': 'UPDATE',
      'id': 10002,
      'message': null,
      'name': 'Sub mid - 3',
      'nextVersion': 2,
      'parentId': 0,
      'platform': '',
      'status': 'ENABLED',
      'updated': null,
      'updatedBy': null
    }
  ],
  'childrenId': [10001, 10002],
  'companyName': 'Merchant 0',
  'companyUrl': null,
  'contactEmail': 'support@devcode.se',
  'contactPerson': 'technicalsupport@bambora.com',
  'contactPhone': '123',
  'created': null,
  'createdBy': null,
  'customerId': 2,
  'description': 'PaymentIQ',
  'enabled': true,
  'event': 'UPDATE',
  'id': 0,
  'message': null,
  'name': 'Mid - 1',
  'nextVersion': 2,
  'parentId': null,
  'platform': null,
  'status': 'ENABLED',
  'updated': null,
  'updatedBy': null
}

/*
  PIQ returns the mids staring as a single mid, containing children which in turn potentially contain children and so on.
  Each level of children represents a level of hierarchy which we display as indentation in the dropdown. The indentation
  is based on the className we apply to each mid-object: parent-mid-{n} where parent-mid-0 represents the highest level.
*/

test('Parses an tree structure of mids from PIQ and returns active enabled an array of object as dropdown objects', () => {
  expect(parseMerchants(merchantRawData)).toStrictEqual([
    {
      "className": "parent-mid parent-mid-0 has-children-mid",
      "key": 0,
      "text": "Mid - 1",
      "value": 0,
    },
    {
      "className": "parent-mid parent-mid-1 has-children-mid",
      "key": 10001,
      "text": "Sub mid - 1",
      "value": 10001,
    },
    {
      "className": "parent-mid parent-mid-2 has-children-mid",
      "key": 100011,
      "text": "Sub sub mid - 1",
      "value": 100011,
    },
    {
      "className": "parent-mid parent-mid-3",
      "key": 10001100,
      "text": "Sub sub sub mid - 1",
      "value": 10001100,
    },
    {
      "className": "parent-mid parent-mid-1",
      "key": 10002,
      "text": "Sub mid - 3",
      "value": 10002,
    }
  ])
})
