import { metadataResponse } from './metadata-mock'

export const metadata = metadataResponse

export const roles = [
  "ROLE_AGENT",
  "ROLE_MERCHANT_SUPPORT",
  "ROLE_MINIBANK",
  "ROLE_INVESTIGATOR",
  "ROLE_USER_PSP_ACCOUNT",
  "ROLE_INVESTIGATOR_ADMIN",
  "ROLE_EXPERIMENTAL_FEATURES",
  "ROLE_OPERATOR_ADMIN",
  "ROLE_BAMBORA_OB_ADMIN",
  "ROLE_EDIT_USER_PSP_ACCOUNT",
  "ROLE_ANALYTICS",
  "ROLE_STORE",
  "ROLE_KYC",
  "ROLE_USER_PSP_ACCOUNT_ADMIN",
  "ROLE_RULES",
  "ROLE_IIN_ADMIN",
  "ROLE_MAINTENANCE_ADMIN",
  "ROLE_RULES_ADMIN",
  "ROLE_DATA_VIEWER",
  "ROLE_CONFIG_ADMIN",
  "ROLE_FIRST_APPROVER",
  "ROLE_ADMIN_APPROVER",
  "ROLE_MERCHANT_ADMIN",
  "ROLE_SECOND_APPROVER",
  "ROLE_IIN",
  "ROLE_TRANSACTION_DETAIL_VIEWER",
  "ROLE_MAINTENANCE_SUPPORT",
  "ROLE_STORE_ADMIN",
  "ROLE_MINIBANK_ADMIN",
  "ROLE_KYC_ADMIN",
  "ROLE_ANALYTICS_ADMIN"
]
